spring:
    application:
        name: flight-pax-test

info:
    version: "@project.version@"
    build:
        artifact: "@project.artifactId@"
        name: "@project.name@"
        version: "@project.version@"
        stage: ${spring.profiles.active}


logging:
    level:
        org.springframework.data: 'DEBUG'
        org.springframework.web: 'DEBUG'
        com.deolan: 'DEBUG'
        com.netflix.discovery: 'DEBUG'
        com.netflix.zuul: 'DEBUG'


eureka:
    instance:
      prefer-ip-address: 'true'
    client:
        registerWithEureka: 'false'
        fetchRegistry: 'true'
        serviceUrl:
            defaultZone: 'http://localhost:8761/eureka/'

