spring:
    application:
        name: feign-localdate-bug

info:
    version: "@project.version@"
    build:
        artifact: "@project.artifactId@"
        name: "@project.name@"
        version: "@project.version@"
        stage: ${spring.profiles.active}


server:
    port: 8088

logging:
    level:
        org.springframework.data: 'DEBUG'
        org.springframework.web: 'DEBUG'
        com.netflix.discovery: 'DEBUG'
        com.netflix.zuul: 'DEBUG'


eureka:
    instance:
      prefer-ip-address: 'true'
    client:
        fetchRegistry: 'true'
        serviceUrl:
            defaultZone: 'http://localhost:8761/eureka/'

